// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"brl/rpc/article/article"
	"brl/rpc/article/internal/logic"
	"brl/rpc/article/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	article.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Ping(ctx context.Context, in *article.Request) (*article.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
