// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type AddUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AddUserResp struct {
	Id int64 `json:"id"`
}

type UserUpdateNickNameReq struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
}

type UserUpdateNickNameResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type DelUserReq struct {
	Id int64 `json:"id"`
}

type DelUserResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}
